### ISSUE TITLE
Unsubscribe warning formatting displaying incorrectly

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruption-manage#113]
<img width="695" alt="Screenshot 2020-11-04 at 14 25 54" src="https://user-images.githubusercontent.com/10854265/98127551-bf721680-1eae-11eb-95ec-6079605cfab3.png">

**Comment by catiarodriguescosta** [comment]
https://github.com/wmcadigital/wmn-design-system/pull/488
