### ISSUE TITLE
Use lowercase 'P' for 'preferences' in the 'Edit your contact preferences' button

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-disruption-manage#119]
Pretty much self-explanatory from the title, change the capital 'P' to a lowercase 'p' in the 'Edit your contact preferences' button.

**Current Behaviour:**
![Screenshot 2020-11-05 at 08 18 59](https://user-images.githubusercontent.com/62507489/98215335-92217900-1f3f-11eb-8a3b-73f5fc603889.png)

**Comment by mrmjprice** [comment]
Fixed in #111
