### ISSUE TITLE
Check copy for confirming SMS - bit block-y

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruption-manage#151]
![IMG_0277](https://user-images.githubusercontent.com/10854265/98786805-87129100-23f6-11eb-92bd-c3ffc24d038d.PNG)

Can we try and split this up/make it simpler?

**Comment by jkmnch** [comment]
### Proposed copy change:


>We'll send text message disruption alerts to **[phone number]**. 
>
>To receive text message alerts, you need to confirm your mobile phone number.
>
>We've sent you a text message with an authentication code. This code will expire at midnight.
>
>If you do not receive the authentication code after 5 minutes, you can resend it.

**Comment by catiarodriguescosta** [comment]
The copy is updated now but it is still not live!
