### ISSUE TITLE
Roads alerts

### ISSUE THREAD

**Issue by DavidS-RTCC** [wmcadigital/wmn-disruption-manage#251]
Hi - when I sign up for road alerts (25 June), the email arrives with WMNetwork branding and a WMNetwork email address. Shouldn't this all be TfWM now?

![image](https://user-images.githubusercontent.com/73537253/123461162-a9050080-d5e0-11eb-899d-280afa8c1717.png)

**Comment by gldgrnt** [comment]
Yes this should be! It'll be updated in the when [this PR](https://github.com/wmcadigital/wmn-disruption-email-templates/pull/41) is merged 👍🏾
